version: 2.1

executors:
  default:
    docker:
      - image: koboriakira/njpw-world-search

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-and-test:
    executor: default
    steps:
      - checkout
      - run:
          command: |
            pip install pipenv
            pipenv lock -r > requirements.txt
            pip install -r requirements.txt
          name: install dependencies
      - run:
          command: python -m pytest --junitxml=test-results/junit.xml
          name: Test
      # テストサマリーに表示するテスト結果をアップロードします
      # https://circleci.com/ja/docs/2.0/collect-test-data/
      - store_test_results:
          path: test-results
      - slack/status:
          fail_only: true
          mentions: 'kobori'
          webhook: $SLACK_DEVELOPMENT_WEBHOOK
workflows:
  main:
    jobs:
      - build-and-test
